version: '3.7'
services:
  
  ensdemo:
    build:
      context: .
    image: ensdemo:latest
    hostname: ensdemo
    command: --check-caps false
    ports:
#    - "51776:51773" # 51773 is the superserver default port
    - "51776:1972"  # 1972 is the new superserver default port
    - "52776:52773" # 52773 is the webserver/management portal port
    volumes:
    - type: bind
      source: .
      target: /src
